<?xml version="1.0" encoding="UTF-8"?>
<!--
 This is a WordPress eXtended RSS file generated by WordPress as an export of your site.
 It contains information about your site's posts, pages, comments, categories, and other content.
 You may use this file to transfer that content from one site to another.
 This file is not intended to serve as a complete backup of your site.

 To import this information into a WordPress site follow these steps:
 1. Log in to that site as an administrator.
 2. Go to Tools: Import in the WordPress admin panel.
 3. Install the "WordPress" importer from the list.
 4. Activate & Run Importer.
 5. Upload this file using the form provided on that page.
 6. You will first be asked to map the authors in this export file to users
    on the site. For each author, you may choose to map to an
    existing user on the site or to create a new user.
 7. WordPress will then import each of the posts, pages, comments, categories, etc.
    contained in this file into your site.
-->
<!-- generator="WordPress.com" created="2024-03-27 03:28"-->
<rss version="2.0" xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:wfw="http://wellformedweb.org/CommentAPI/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:wp="http://wordpress.org/export/1.2/">
  <channel>
<title>TODO HACERCA DEL BMX</title>
<link>https://digu33.wordpress.com</link>
<description>Todo sobre el bmx</description>
<pubDate>Wed, 27 Mar 2024 03:28:13 +0000</pubDate>
<language>es</language>
<wp:wxr_version>1.2</wp:wxr_version>
<wp:base_site_url>http://wordpress.com/</wp:base_site_url>
<wp:base_blog_url>https://digu33.wordpress.com</wp:base_blog_url>
<wp:author>
  <wp:author_id>248557932</wp:author_id>
  <wp:author_login>xk5dd6dzhw</wp:author_login>
  <wp:author_email>xk5dd6dzhw@privaterelay.appleid.com</wp:author_email>
  <wp:author_display_name><![CDATA[Danny Caicedo]]></wp:author_display_name>
  <wp:author_first_name><![CDATA[]]></wp:author_first_name>
  <wp:author_last_name><![CDATA[]]></wp:author_last_name>
</wp:author>
<wp:category>
  <wp:term_id>1771</wp:term_id>
  <wp:category_nicename>sin-categoria</wp:category_nicename>
  <wp:category_parent/>
  <wp:cat_name><![CDATA[Sin categoría]]></wp:cat_name>
</wp:category>
<generator>http://wordpress.com/</generator>

<image>
	<url>https://digu33.wordpress.com/wp-content/uploads/2024/03/descarga-4.jpg?w=32</url>
	<title>TODO HACERCA DEL BMX</title>
	<link>https://digu33.wordpress.com</link>
	<width>32</width>
	<height>32</height>
</image> 
<item>
  <title><![CDATA[Acerca de]]></title>
  <link>https://digu33.wordpress.com/acerca-de/</link>
  <pubDate>Wed, 27 Mar 2024 01:20:05 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">http://digu33.wordpress.com/?page_id=1</guid>
  <description/>
  <content:encoded><![CDATA[<!-- wp:paragraph -->
<p>Este es un ejemplo de página. A diferencia de las entradas, que se muestran en la página de inicio de tu blog en el orden en que se publicaron, las páginas se ajustan mejor a un contenido atemporal que usted quiere que sean más accesibles, como tus datos de contacto o la información acerca de ti. Haz clic en el enlace “Editar” para realizar cambios en esta página o <a title="Enlace directo para añadir una página nueva en el escritorio" href="https://wordpress.com/page/231286805/new/">añadir otra página</a>.</p>
<!-- /wp:paragraph -->]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>1</wp:post_id>
  <wp:post_date>2024-03-27 01:20:05</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:20:05</wp:post_date_gmt>
  <wp:post_modified>2024-03-27 01:20:05</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:20:05</wp:post_modified_gmt>
  <wp:comment_status>closed</wp:comment_status>
  <wp:ping_status>open</wp:ping_status>
  <wp:post_name>acerca-de</wp:post_name>
  <wp:status>publish</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>page</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <wp:postmeta>
    <wp:meta_key>_wp_page_template</wp:meta_key>
    <wp:meta_value><![CDATA[default]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_last_editor_used_jetpack</wp:meta_key>
    <wp:meta_value><![CDATA[block-editor]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[examenalexisgordonweb.rar_.txt]]></title>
  <link>https://digu33.wordpress.com/?attachment_id=3</link>
  <pubDate>Wed, 27 Mar 2024 01:24:02 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">http://digu33.files.wordpress.com/2024/03/examenalexisgordonweb.rar_.txt</guid>
  <description/>
  <content:encoded><![CDATA[http://digu33.wordpress.com/wp-content/uploads/2024/03/examenalexisgordonweb.rar_.txt]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>3</wp:post_id>
  <wp:post_date>2024-03-26 20:24:02</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:24:02</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:24:02</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:24:02</wp:post_modified_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>examenalexisgordonweb-rar_-txt</wp:post_name>
  <wp:status>private</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>attachment</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <wp:attachment_url>https://digu33.wordpress.com/wp-content/uploads/2024/03/examenalexisgordonweb.rar_.txt</wp:attachment_url>
  <wp:postmeta>
    <wp:meta_key>_wp_attached_file</wp:meta_key>
    <wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/examenalexisgordonweb.rar_.txt]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wp_attachment_context</wp:meta_key>
    <wp:meta_value><![CDATA[import]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>import_blog_id</wp:meta_key>
    <wp:meta_value><![CDATA[231286805]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[Custom Styles]]></title>
  <link>https://digu33.wordpress.com/2024/03/26/wp-global-styles-pub%2ftwentytwentyfour/</link>
  <pubDate>Wed, 27 Mar 2024 01:24:38 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">https://digu33.wordpress.com/2024/03/26/wp-global-styles-pub%2ftwentytwentyfour/</guid>
  <description/>
  <content:encoded><![CDATA[{"version":2,"isGlobalStylesUserThemeJSON":true}]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>4</wp:post_id>
  <wp:post_date>2024-03-26 20:24:38</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:24:38</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:24:38</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:24:38</wp:post_modified_gmt>
  <wp:comment_status>closed</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>wp-global-styles-pub%2ftwentytwentyfour</wp:post_name>
  <wp:status>publish</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>wp_global_styles</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <category domain="wp_theme" nicename="twentytwentyfour"><![CDATA[twentytwentyfour]]></category>
  <wp:postmeta>
    <wp:meta_key>_publicize_pending</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[Crecimiento desbloqueado]]></title>
  <link>https://digu33.wordpress.com/2024/03/26/crecimiento-desbloqueado-2/</link>
  <pubDate>Wed, 27 Mar 2024 01:31:16 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">https://digu33.wordpress.com/2024/03/26/crecimiento-desbloqueado-2/</guid>
  <description/>
  <content:encoded><![CDATA[<!-- wp:paragraph -->
<p>Te damos la bienvenida a WordPress. Esta es una entrada de ejemplo. Empieza tu andadura en el mundo bloguero editándola o borrándola. Para añadir más contenido aquí, haz clic en el pequeño icono del signo más situado en la esquina superior izquierda. Allí encontrarás una selección de bloques y patrones de WordPress que se adaptan a todas tus necesidades de creación de contenidos. Y no te olvides de echar un vistazo a la vista de lista: haz clic en el icono que hay unos puntos a la derecha del icono del signo más y obtendrás una lista ordenada y fácil de ver de los bloques y patrones de tu entrada.</p>
<!-- /wp:paragraph -->]]></content:encoded>
  <excerpt:encoded><![CDATA[Cada empresa tiene un potencial único que espera ser aprovechado. Reconocer las claves para desbloquear este crecimiento puede encaminar a una empresa hacia un éxito sin precedentes.]]></excerpt:encoded>
  <wp:post_id>21</wp:post_id>
  <wp:post_date>2024-03-26 20:31:16</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:31:16</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:31:16</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:31:16</wp:post_modified_gmt>
  <wp:comment_status>closed</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>crecimiento-desbloqueado-2</wp:post_name>
  <wp:status>publish</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>post</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <category domain="category" nicename="sin-categoria"><![CDATA[Sin categoría]]></category>
  <wp:postmeta>
    <wp:meta_key>_headstart_post</wp:meta_key>
    <wp:meta_value><![CDATA[_hs_extra]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>sharing_disabled</wp:meta_key>
    <wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>switch_like_status</wp:meta_key>
    <wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_starter_page_template</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_hs_old_id</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wpas_skip_all_services</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_jetpack_memberships_contains_paid_content</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_jetpack_memberships_contains_paywalled_content</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_publicize_pending</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_thumbnail_id</wp:meta_key>
    <wp:meta_value><![CDATA[27]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[Magia de la colaboración]]></title>
  <link>https://digu33.wordpress.com/2024/03/26/magia-de-la-colaboracion-2/</link>
  <pubDate>Wed, 27 Mar 2024 01:31:15 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">https://digu33.wordpress.com/2024/03/26/magia-de-la-colaboracion-2/</guid>
  <description/>
  <content:encoded><![CDATA[<!-- wp:paragraph -->
<p>Te damos la bienvenida a WordPress. Esta es una entrada de ejemplo. Empieza tu andadura en el mundo bloguero editándola o borrándola. Para añadir más contenido aquí, haz clic en el pequeño icono del signo más situado en la esquina superior izquierda. Allí encontrarás una selección de bloques y patrones de WordPress que se adaptan a todas tus necesidades de creación de contenidos. Y no te olvides de echar un vistazo a la vista de lista: haz clic en el icono que hay unos puntos a la derecha del icono del signo más y obtendrás una lista ordenada y fácil de ver de los bloques y patrones de tu entrada.</p>
<!-- /wp:paragraph -->]]></content:encoded>
  <excerpt:encoded><![CDATA[La magia que surge de una colaboración eficaz es innegable. Cuando convergen mentes diversas con un propósito común, los resultados pueden ser transformadores.]]></excerpt:encoded>
  <wp:post_id>22</wp:post_id>
  <wp:post_date>2024-03-26 20:31:15</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:31:15</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:31:15</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:31:15</wp:post_modified_gmt>
  <wp:comment_status>closed</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>magia-de-la-colaboracion-2</wp:post_name>
  <wp:status>publish</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>post</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <category domain="category" nicename="sin-categoria"><![CDATA[Sin categoría]]></category>
  <wp:postmeta>
    <wp:meta_key>_publicize_pending</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_jetpack_memberships_contains_paywalled_content</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_jetpack_memberships_contains_paid_content</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_headstart_post</wp:meta_key>
    <wp:meta_value><![CDATA[_hs_extra]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>sharing_disabled</wp:meta_key>
    <wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>switch_like_status</wp:meta_key>
    <wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_starter_page_template</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_hs_old_id</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wpas_skip_all_services</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[Ventaja adaptativa]]></title>
  <link>https://digu33.wordpress.com/2024/03/26/ventaja-adaptativa-2/</link>
  <pubDate>Wed, 27 Mar 2024 01:31:13 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">https://digu33.wordpress.com/2024/03/26/ventaja-adaptativa-2/</guid>
  <description/>
  <content:encoded><![CDATA[<!-- wp:paragraph -->
<p>Te damos la bienvenida a WordPress. Esta es una entrada de ejemplo. Empieza tu andadura en el mundo bloguero editándola o borrándola. Para añadir más contenido aquí, haz clic en el pequeño icono del signo más situado en la esquina superior izquierda. Allí encontrarás una selección de bloques y patrones de WordPress que se adaptan a todas tus necesidades de creación de contenidos. Y no te olvides de echar un vistazo a la vista de lista: haz clic en el icono que hay unos puntos a la derecha del icono del signo más y obtendrás una lista ordenada y fácil de ver de los bloques y patrones de tu entrada.</p>
<!-- /wp:paragraph -->]]></content:encoded>
  <excerpt:encoded><![CDATA[En un panorama empresarial en constante cambio, la adaptabilidad no es solo un rasgo: es una ventaja competitiva. Las empresas que aceptan el cambio, aprenden de los retos y pivotan cuando es necesario son las que no solo sobreviven, sino que prosperan en entornos inciertos.]]></excerpt:encoded>
  <wp:post_id>24</wp:post_id>
  <wp:post_date>2024-03-26 20:31:13</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:31:13</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:31:13</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:31:13</wp:post_modified_gmt>
  <wp:comment_status>closed</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>ventaja-adaptativa-2</wp:post_name>
  <wp:status>publish</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>post</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <category domain="category" nicename="sin-categoria"><![CDATA[Sin categoría]]></category>
  <wp:postmeta>
    <wp:meta_key>_starter_page_template</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>switch_like_status</wp:meta_key>
    <wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>sharing_disabled</wp:meta_key>
    <wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_headstart_post</wp:meta_key>
    <wp:meta_value><![CDATA[_hs_extra]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_jetpack_memberships_contains_paid_content</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_hs_old_id</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wpas_skip_all_services</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_publicize_pending</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_jetpack_memberships_contains_paywalled_content</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[Placeholder Image]]></title>
  <link>https://digu33.wordpress.com/2024/03/26/mas-alla-del-obstaculo-2/placeholder-image-5/</link>
  <pubDate>Wed, 27 Mar 2024 01:36:28 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">http://digu33.files.wordpress.com/2024/03/1ceb1-tt4_post_2-1.jpg</guid>
  <description/>
  <content:encoded><![CDATA[]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>26</wp:post_id>
  <wp:post_date>2024-03-26 20:36:28</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:36:28</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:36:28</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:36:28</wp:post_modified_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>placeholder-image-5</wp:post_name>
  <wp:status>inherit</wp:status>
  <wp:post_parent>20</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>attachment</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <wp:attachment_url>https://digu33.wordpress.com/wp-content/uploads/2024/03/1ceb1-tt4_post_2-1.jpg</wp:attachment_url>
  <wp:postmeta>
    <wp:meta_key>_wp_attached_file</wp:meta_key>
    <wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/1ceb1-tt4_post_2-1.jpg]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wp_attachment_metadata</wp:meta_key>
    <wp:meta_value><![CDATA[a:6:{s:5:"width";i:800;s:6:"height";i:907;s:4:"file";s:95:"/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/1ceb1-tt4_post_2-1.jpg";s:8:"filesize";i:100686;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[Placeholder Image]]></title>
  <link>https://digu33.wordpress.com/2024/03/26/crecimiento-desbloqueado-2/placeholder-image-6/</link>
  <pubDate>Wed, 27 Mar 2024 01:36:28 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">http://digu33.files.wordpress.com/2024/03/b3f2c-tt4_post_3-scaled-1-1.jpg</guid>
  <description/>
  <content:encoded><![CDATA[]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>27</wp:post_id>
  <wp:post_date>2024-03-26 20:36:28</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:36:28</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:36:28</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:36:28</wp:post_modified_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>placeholder-image-6</wp:post_name>
  <wp:status>inherit</wp:status>
  <wp:post_parent>21</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>attachment</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <wp:attachment_url>https://digu33.wordpress.com/wp-content/uploads/2024/03/b3f2c-tt4_post_3-scaled-1-1.jpg</wp:attachment_url>
  <wp:postmeta>
    <wp:meta_key>_wp_attached_file</wp:meta_key>
    <wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/b3f2c-tt4_post_3-scaled-1-1.jpg]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wp_attachment_metadata</wp:meta_key>
    <wp:meta_value><![CDATA[a:6:{s:5:"width";i:800;s:6:"height";i:534;s:4:"file";s:104:"/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/b3f2c-tt4_post_3-scaled-1-1.jpg";s:8:"filesize";i:54514;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[images]]></title>
  <link>https://digu33.wordpress.com/images/</link>
  <pubDate>Wed, 27 Mar 2024 01:45:58 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">http://digu33.files.wordpress.com/2024/03/images.jpg</guid>
  <description/>
  <content:encoded><![CDATA[]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>30</wp:post_id>
  <wp:post_date>2024-03-26 20:45:58</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:45:58</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:45:58</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:45:58</wp:post_modified_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>images</wp:post_name>
  <wp:status>inherit</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>attachment</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <wp:attachment_url>https://digu33.wordpress.com/wp-content/uploads/2024/03/images.jpg</wp:attachment_url>
  <wp:postmeta>
    <wp:meta_key>_wp_attached_file</wp:meta_key>
    <wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/images.jpg]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wp_attachment_metadata</wp:meta_key>
    <wp:meta_value><![CDATA[a:6:{s:5:"width";i:194;s:6:"height";i:259;s:4:"file";s:83:"/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/images.jpg";s:8:"filesize";i:11129;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[Inicio del blog]]></title>
  <link>https://digu33.wordpress.com/2024/03/26/home/</link>
  <pubDate>Wed, 27 Mar 2024 01:48:44 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">https://digu33.wordpress.com/2024/03/26/home/</guid>
  <description/>
  <content:encoded><![CDATA[<!-- wp:template-part {"slug":"header","theme":"twentytwentyfour","tagName":"header","area":"header"} /-->

<!-- wp:group {"tagName":"main","style":{"spacing":{"blockGap":"0","margin":{"top":"0"}}},"layout":{"type":"default"}} -->
<main class="wp-block-group" style="margin-top:0"><!-- wp:group {"metadata":{"categories":["banner","call-to-action","featured"]},"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50","right":"var:preset|spacing|50"}}},"layout":{"type":"constrained","contentSize":"","wideSize":""}} -->
<div class="wp-block-group alignfull" style="padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)"><!-- wp:group {"style":{"spacing":{"blockGap":"0px"}},"layout":{"type":"constrained","contentSize":"565px"}} -->
<div class="wp-block-group"><!-- wp:heading {"textAlign":"center","level":1,"fontSize":"x-large"} -->
<h1 class="wp-block-heading has-text-align-center has-x-large-font-size">De E.T. a los Juegos: La increíble historia del BMX Freestyle</h1>
<!-- /wp:heading -->

<!-- wp:spacer {"height":"1.25rem"} -->
<div style="height:1.25rem" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">El BMX Freestyle está por vivir su máximo momento de gloria. Mientras esperamos su debut, repasamos la sorprendente historia de este deporte. ¡Vamos!</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":"var:preset|spacing|30","style":{"layout":[]}} -->
<div style="height:var(--wp--preset--spacing--30)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:image {"id":38,"sizeSlug":"full","linkDestination":"none","align":"wide","className":"is-style-rounded"} -->
<figure class="wp-block-image alignwide size-full is-style-rounded"><img src="https://digu33.wordpress.com/wp-content/uploads/2024/03/images-2.jpg" alt="" class="wp-image-38" /></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"categories":["text","about"]},"align":"full","style":{"spacing":{"margin":{"top":"0","bottom":"0"},"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50","right":"var:preset|spacing|50"}}},"backgroundColor":"base-2","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-base-2-background-color has-background" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)"><!-- wp:group {"style":{"spacing":{"blockGap":"0px"}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group"><!-- wp:heading {"textAlign":"center","className":"is-style-asterisk"} -->
<h2 class="wp-block-heading has-text-align-center is-style-asterisk">Street</h2>
<!-- /wp:heading -->

<!-- wp:spacer {"height":"0px","style":{"layout":{"flexSize":"1.25rem","selfStretch":"fixed"}}} -->
<div style="height:0px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">El hispano-nigeriano <a href="https://www.redbull.com/es-es/athlete/courage-adams">Courage Adams</a> se las sabe todas en esta disciplina del BMX que consiste en <strong>planchar los trucos en obstáculos callejeros de todo tipo como bancos, paredes, escaleras, barandillas, etc. </strong>Aquí, cualquier ciudad con una arquitectura que se preste como Madrid o Barcelona, es buena para practicarlo. Precisamente en la Ciudad Condal se realiza La Última Street, un evento que siempre tiene lugar a finales de año y que reúne a muchos riders en un ambiente totalmente ‘festivo’ e itinerante por varios spots de la urbe.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":"var:preset|spacing|40","style":{"spacing":{"margin":{"top":"0","bottom":"0"}}}} -->
<div style="margin-top:0;margin-bottom:0;height:var(--wp--preset--spacing--40)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"top":"var:preset|spacing|30","left":"var:preset|spacing|40"}}}} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"style":{"spacing":{"blockGap":"var:preset|spacing|10"}}} -->
<div class="wp-block-column"><!-- wp:heading {"textAlign":"left","level":3,"style":{"typography":{"fontStyle":"normal","fontWeight":"600"}},"className":"is-style-asterisk","fontSize":"medium","fontFamily":"body"} -->
<h3 class="wp-block-heading has-text-align-left is-style-asterisk has-body-font-family has-medium-font-size" style="font-style:normal;font-weight:600">BMX: siglas e historia</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Las&nbsp;<strong>siglas BMX significan Bicycle MotoCross&nbsp;</strong>y tienen que ver con la&nbsp;<a rel="noreferrer noopener" href="http://historiadelbmx45.blogspot.com/" target="_blank">historia de este deporte</a>, que se remonta a 1969. Fue entonces cuando en California -dónde si no-<strong>&nbsp;los jóvenes empezaron a usar sus bicis en pistas de Motocross&nbsp;</strong>para imitar a sus ídolos motorizados. Viendo la tendencia, un fabricante empezó a producir bicis parecidas a las motos y el deporte se expandiría. No sería hasta unos años más tarde cuando llegaría a Europa.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Existen dos grandes disciplinas o&nbsp;<strong>modalidades de BMX: Race y Freestyle.&nbsp;</strong>Esta segunda, además, tiene varias subdisciplinas.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"spacing":{"blockGap":"var:preset|spacing|10"}}} -->
<div class="wp-block-column"><!-- wp:heading {"textAlign":"left","level":3,"style":{"typography":{"fontStyle":"normal","fontWeight":"600"}},"className":"is-style-asterisk","fontSize":"medium","fontFamily":"body"} -->
<h3 class="wp-block-heading has-text-align-left is-style-asterisk has-body-font-family has-medium-font-size" style="font-style:normal;font-weight:600">BMX Race</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"left"} -->
<p class="has-text-align-left">Dado el lugar y el motivo de su nacimiento, la modalidad original es el BMX Race, que consiste en<strong> carreras por pistas parecidas a las de Motocross</strong>. <strong>Con una diferencia:</strong> la tierra en lugar de húmeda es arena arcillosa compacta para evitar incrustaciones en las ruedas de la bici. El objetivo no es otro que el de cualquier otra carrera: ser más rápido que el rival, ya sea compitiendo de manera simultánea como en contrarreloj.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"spacing":{"blockGap":"var:preset|spacing|10"}}} -->
<div class="wp-block-column"><!-- wp:heading {"textAlign":"left","level":3,"style":{"typography":{"fontStyle":"normal","fontWeight":"600"}},"className":"is-style-asterisk","fontSize":"medium","fontFamily":"body"} -->
<h3 class="wp-block-heading has-text-align-left is-style-asterisk has-body-font-family has-medium-font-size" style="font-style:normal;font-weight:600">BMX Freestyle</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"left"} -->
<p class="has-text-align-left">Con la aparición de los skateparks, los bikers que usaban BMX empezaron también a tomar estos spots y a probar <strong>‘trucos’. Aquí nació el BMX Freestyle</strong>, que consiste en realizar trucos con la bici. Esta disciplina tiene varias subdisciplinas: Dirt Jump, Flatland, Park/Bowl, Street, Vert y Big Air.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:spacer {"height":"var:preset|spacing|20"} -->
<div style="height:var(--wp--preset--spacing--20)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"top":"var:preset|spacing|30","left":"var:preset|spacing|40"}}}} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"style":{"spacing":{"blockGap":"var:preset|spacing|10"}}} -->
<div class="wp-block-column"><!-- wp:paragraph {"align":"left"} -->
<p class="has-text-align-left"></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"spacing":{"blockGap":"var:preset|spacing|10"}}} -->
<div class="wp-block-column"></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"spacing":{"blockGap":"var:preset|spacing|10"}}} -->
<div class="wp-block-column"></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"categories":["text","about"]},"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50","right":"var:preset|spacing|50"},"margin":{"top":"0","bottom":"0"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)"><!-- wp:group {"align":"wide","style":{"spacing":{"blockGap":"0"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide"><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|10"}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group"><!-- wp:heading {"textAlign":"center","className":"is-style-asterisk"} -->
<h2 class="wp-block-heading has-text-align-center is-style-asterisk">Partes y espesificaciones de una bmx</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":"var:preset|spacing|40"} -->
<div style="height:var(--wp--preset--spacing--40)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"top":"var:preset|spacing|50","left":"var:preset|spacing|60"}}}} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"verticalAlignment":"center","width":"40%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:40%"><!-- wp:heading {"level":3,"className":"is-style-asterisk"} -->
<h3 class="wp-block-heading is-style-asterisk">CUADRO STRANGER “STEVIE CHURCHILL”</h3>
<!-- /wp:heading -->

<!-- wp:list {"style":{"typography":{"lineHeight":"1.75"}},"className":"is-style-checkmark-list"} -->
<ul style="line-height:1.75" class="is-style-checkmark-list"><!-- wp:list-item -->
<li>Diseñado con Stevie Churchill</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>100% Chromoly</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Punteras cortadas con láser de 6 mm de grosor con tensores de cadena integrados</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>5″ headtube</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>75.3 HT</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>11.7″ BB</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>13.25″ CS</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>9″ Standover</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>s</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"50%"} -->
<div class="wp-block-column" style="flex-basis:50%"><!-- wp:gallery {"ids":[null],"linkTo":"none"} -->
<figure class="wp-block-gallery has-nested-images columns-default is-cropped"><!-- wp:image {"id":34,"sizeSlug":"large","linkDestination":"none","className":"is-style-rounded"} -->
<figure class="wp-block-image size-large is-style-rounded"><img src="https://digu33.wordpress.com/wp-content/uploads/2024/03/cuadro-stranger-churchill1.jpg?w=935" alt="" class="wp-image-34" /></figure>
<!-- /wp:image --></figure>
<!-- /wp:gallery --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:spacer {"height":"var:preset|spacing|40"} -->
<div style="height:var(--wp--preset--spacing--40)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"top":"var:preset|spacing|50","left":"var:preset|spacing|60"}}}} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"width":"50%"} -->
<div class="wp-block-column" style="flex-basis:50%"><!-- wp:image {"id":35,"sizeSlug":"full","linkDestination":"none","className":"is-style-rounded"} -->
<figure class="wp-block-image size-full is-style-rounded"><img src="https://digu33.wordpress.com/wp-content/uploads/2024/03/manzana-freecoaster-odyssey-clutch-v2-400x400-1.jpg" alt="" class="wp-image-35" /></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"40%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:40%"><!-- wp:heading {"level":3,"className":"is-style-asterisk"} -->
<h3 class="wp-block-heading is-style-asterisk">MANZANA ODYSSEY FREECOASTER «CLUTCH V2»</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:list {"style":{"typography":{"lineHeight":"1.75"}},"className":"is-style-checkmark-list"} -->
<ul style="line-height:1.75" class="is-style-checkmark-list"><!-- wp:list-item -->
<li>El cubo de embrague es un diseño tradicional de cubo de montaña basado en embrague que elimina todos los elementos problemáticos en los cubos ordinarios y solo conserva las piezas que funcionan. Un eje COMPLETO de 14 mm, una configuración de rodamientos y un diseño de mecanismo de arrastre nuevos y súper fuertes evitan la necesidad de reparaciones constantes. Equipado con ajuste de holgura externo, que se puede hacer con una llave hexagonal de 2,5 mm a través de un orificio de acceso a la cubierta del cubo (se puede ajustar sin quitar la rueda), y una especificación de protección de cubo de plástico mejorada.</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>El mismo eje de la montaña rusa Clutch que te ha encantado, pero con algunas mejoras.</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>CARACTERÍSTICAS</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Diseño de eje de máxima resistencia</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Disposición de rodamientos súper duradera en todo</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Ajuste de holgura con llave hexagonal de 2,5 mm a través del orificio de acceso a la carcasa del cubo. No es necesario desmontar la rueda.</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Diseño de mecanismo de arrastre súper duradero</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Crankflip listo</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Protegido por la patente estadounidense 9,469,157</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Protegido por las patentes de Taiwán M487850, M487851, M502583</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><a href="https://cdn.shopify.com/s/files/1/0703/8345/files/ODSY-Clutch-V2-Technical-Swipe-Flyer-Diagram-Only.jpg">Vista en despiece ordenado «</a></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>MEJORAS SOBRE EL EMBRAGUE V1</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Pernos de eje cromados de 14 mm tanto en el lado de la transmisión como en el opuesto para una mayor confiabilidad</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Compromiso mejorado del embrague</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Precisión de fabricación mejorada en todo</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Más holgura que el concentrador V1</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Nuevas especificaciones de plástico duraderas patentadas para el protector de buje extraíble</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>ESPECIFICACIONES</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><strong>Controlador:</strong> 9T, LHD o RHD</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><strong>Configuración de radios:</strong> 36 orificios</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><strong>Material</strong> de la carcasa del buje: carcasa de aluminio 2014-T6</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><strong>Peso:</strong> 22 oz / 623 g</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Testimonial","categories":["testimonials","text"]},"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60","left":"var:preset|spacing|60","right":"var:preset|spacing|60"},"margin":{"top":"0","bottom":"0"}}},"backgroundColor":"contrast","textColor":"base","layout":{"type":"constrained","contentSize":""}} -->
<div class="wp-block-group alignfull has-base-color has-contrast-background-color has-text-color has-background" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--60);padding-right:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60);padding-left:var(--wp--preset--spacing--60)"><!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"align":"center","style":{"typography":{"lineHeight":"1.2"}},"textColor":"base","fontSize":"x-large","fontFamily":"heading"} -->
<p class="has-text-align-center has-base-color has-text-color has-heading-font-family has-x-large-font-size" style="line-height:1.2"><em>“PRACTICAR TODOS LOS DIAS, TE VOLVERA UNA MAQUINA.”</em></p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":"var:preset|spacing|10"} -->
<div style="height:var(--wp--preset--spacing--10)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:group {"metadata":{"name":"Testimonial source"},"style":{"spacing":{"blockGap":"0"}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:gallery {"linkTo":"none","sizeSlug":"thumbnail","align":"center"} -->
<figure class="wp-block-gallery aligncenter has-nested-images columns-default is-cropped"><!-- wp:image {"id":33,"sizeSlug":"thumbnail","linkDestination":"none"} -->
<figure class="wp-block-image size-thumbnail"><img src="https://digu33.wordpress.com/wp-content/uploads/2024/03/images-1.jpg?w=150" alt="" class="wp-image-33" /></figure>
<!-- /wp:image --></figure>
<!-- /wp:gallery -->

<!-- wp:paragraph {"align":"center","style":{"spacing":{"margin":{"top":"var:preset|spacing|10","bottom":"0"}}}} -->
<p class="has-text-align-center" style="margin-top:var(--wp--preset--spacing--10);margin-bottom:0">STEVIES CHURCHILL</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center","style":{"typography":{"fontStyle":"normal","fontWeight":"300"}},"textColor":"contrast-3","fontSize":"small"} -->
<p class="has-text-align-center has-contrast-3-color has-text-color has-small-font-size" style="font-style:normal;font-weight:300"></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"categories":["posts","posts"]},"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50","right":"var:preset|spacing|50"},"margin":{"top":"0","bottom":"0"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)"><!-- wp:heading {"align":"wide","style":{"typography":{"lineHeight":"1"},"spacing":{"margin":{"top":"0","bottom":"var:preset|spacing|40"}}},"fontSize":"x-large"} -->
<h2 class="wp-block-heading alignwide has-x-large-font-size" style="margin-top:0;margin-bottom:var(--wp--preset--spacing--40);line-height:1">Bmx, Pasion, Accion</h2>
<!-- /wp:heading -->

<!-- wp:group {"align":"wide","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide"><!-- wp:query {"queryId":1,"query":{"perPage":10,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":true},"align":"wide","layout":{"type":"default"}} -->
<div class="wp-block-query alignwide"><!-- wp:post-template -->
<!-- wp:separator {"backgroundColor":"contrast-3","className":"alignwide is-style-wide"} -->
<hr class="wp-block-separator has-text-color has-contrast-3-color has-alpha-channel-opacity has-contrast-3-background-color has-background alignwide is-style-wide" />
<!-- /wp:separator -->

<!-- wp:columns {"verticalAlignment":"center","align":"wide","style":{"spacing":{"margin":{"top":"var:preset|spacing|20","bottom":"var:preset|spacing|20"}}}} -->
<div class="wp-block-columns alignwide are-vertically-aligned-center" style="margin-top:var(--wp--preset--spacing--20);margin-bottom:var(--wp--preset--spacing--20)"><!-- wp:column {"verticalAlignment":"center","width":"72%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:72%"><!-- wp:post-title {"isLink":true,"style":{"typography":{"lineHeight":"1.1","fontSize":"1.5rem"}}} /--></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"28%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:28%"><!-- wp:template-part {"slug":"post-meta","theme":"twentytwentyfour"} /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
<!-- /wp:post-template -->

<!-- wp:spacer {"height":"var:preset|spacing|30"} -->
<div style="height:var(--wp--preset--spacing--30)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:query-pagination {"paginationArrow":"arrow","layout":{"type":"flex","justifyContent":"space-between"}} -->
<!-- wp:query-pagination-previous /-->

<!-- wp:query-pagination-numbers /-->

<!-- wp:query-pagination-next /-->
<!-- /wp:query-pagination -->

<!-- wp:query-no-results -->
<!-- wp:paragraph -->
<p>No posts were found.</p>
<!-- /wp:paragraph -->
<!-- /wp:query-no-results --></div>
<!-- /wp:query --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"categories":["call-to-action"]},"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50","right":"var:preset|spacing|50"},"margin":{"top":"0","bottom":"0"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)"><!-- wp:group {"align":"wide","style":{"border":{"radius":"16px"},"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|50","right":"var:preset|spacing|50"}}},"backgroundColor":"base-2","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide has-base-2-background-color has-background" style="border-radius:16px;padding-top:var(--wp--preset--spacing--40);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--50)"><!-- wp:spacer {"height":"var:preset|spacing|10"} -->
<div style="height:var(--wp--preset--spacing--10)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:heading {"textAlign":"center","fontSize":"x-large"} -->
<h2 class="wp-block-heading has-text-align-center has-x-large-font-size"></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center"></p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":"var:preset|spacing|10"} -->
<div style="height:var(--wp--preset--spacing--10)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></main>
<!-- /wp:group -->

<!-- wp:template-part {"slug":"footer","theme":"twentytwentyfour","tagName":"footer","area":"footer"} /-->]]></content:encoded>
  <excerpt:encoded><![CDATA[Muestra las últimas entradas, así como la página de inicio del sitio o la «página de entradas» definida en los ajustes de lectura. Si existe, la plantilla de página de inicio sobrescribirá a esta plantilla cuando se muestren las entradas en dicha página de inicio.]]></excerpt:encoded>
  <wp:post_id>31</wp:post_id>
  <wp:post_date>2024-03-26 20:48:44</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:48:44</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 21:19:37</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 02:19:37</wp:post_modified_gmt>
  <wp:comment_status>closed</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>home</wp:post_name>
  <wp:status>publish</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>wp_template</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <category domain="wp_theme" nicename="twentytwentyfour"><![CDATA[twentytwentyfour]]></category>
  <wp:postmeta>
    <wp:meta_key>origin</wp:meta_key>
    <wp:meta_value><![CDATA[theme]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_publicize_pending</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[Placeholder Image]]></title>
  <link>https://digu33.wordpress.com/placeholder-image/</link>
  <pubDate>Wed, 27 Mar 2024 01:26:51 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">http://digu33.files.wordpress.com/2024/03/0565b-tt4_post_1.jpg</guid>
  <description/>
  <content:encoded><![CDATA[]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>12</wp:post_id>
  <wp:post_date>2024-03-26 20:26:51</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:26:51</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:26:51</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:26:51</wp:post_modified_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>placeholder-image</wp:post_name>
  <wp:status>inherit</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>attachment</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <wp:attachment_url>https://digu33.wordpress.com/wp-content/uploads/2024/03/0565b-tt4_post_1.jpg</wp:attachment_url>
  <wp:postmeta>
    <wp:meta_key>_wp_attached_file</wp:meta_key>
    <wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/0565b-tt4_post_1.jpg]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wp_attachment_metadata</wp:meta_key>
    <wp:meta_value><![CDATA[a:6:{s:5:"width";i:800;s:6:"height";i:1158;s:4:"file";s:93:"/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/0565b-tt4_post_1.jpg";s:8:"filesize";i:81573;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[Placeholder Image]]></title>
  <link>https://digu33.wordpress.com/placeholder-image-2/</link>
  <pubDate>Wed, 27 Mar 2024 01:26:53 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">http://digu33.files.wordpress.com/2024/03/1ceb1-tt4_post_2.jpg</guid>
  <description/>
  <content:encoded><![CDATA[]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>13</wp:post_id>
  <wp:post_date>2024-03-26 20:26:53</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:26:53</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:26:53</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:26:53</wp:post_modified_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>placeholder-image-2</wp:post_name>
  <wp:status>inherit</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>attachment</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <wp:attachment_url>https://digu33.wordpress.com/wp-content/uploads/2024/03/1ceb1-tt4_post_2.jpg</wp:attachment_url>
  <wp:postmeta>
    <wp:meta_key>_wp_attached_file</wp:meta_key>
    <wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/1ceb1-tt4_post_2.jpg]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wp_attachment_metadata</wp:meta_key>
    <wp:meta_value><![CDATA[a:6:{s:5:"width";i:800;s:6:"height";i:907;s:4:"file";s:93:"/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/1ceb1-tt4_post_2.jpg";s:8:"filesize";i:100686;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[Placeholder Image]]></title>
  <link>https://digu33.wordpress.com/placeholder-image-3/</link>
  <pubDate>Wed, 27 Mar 2024 01:26:54 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">http://digu33.files.wordpress.com/2024/03/b3f2c-tt4_post_3-scaled-1.jpg</guid>
  <description/>
  <content:encoded><![CDATA[]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>14</wp:post_id>
  <wp:post_date>2024-03-26 20:26:54</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:26:54</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:26:54</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:26:54</wp:post_modified_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>placeholder-image-3</wp:post_name>
  <wp:status>inherit</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>attachment</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <wp:attachment_url>https://digu33.wordpress.com/wp-content/uploads/2024/03/b3f2c-tt4_post_3-scaled-1.jpg</wp:attachment_url>
  <wp:postmeta>
    <wp:meta_key>_wp_attached_file</wp:meta_key>
    <wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/b3f2c-tt4_post_3-scaled-1.jpg]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wp_attachment_metadata</wp:meta_key>
    <wp:meta_value><![CDATA[a:6:{s:5:"width";i:800;s:6:"height";i:534;s:4:"file";s:102:"/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/b3f2c-tt4_post_3-scaled-1.jpg";s:8:"filesize";i:54514;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[Navegación]]></title>
  <link>https://digu33.wordpress.com/2024/03/26/navigation/</link>
  <pubDate>Wed, 27 Mar 2024 01:36:33 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">https://digu33.wordpress.com/2024/03/26/navigation/</guid>
  <description/>
  <content:encoded><![CDATA[<!-- wp:page-list /-->]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>28</wp:post_id>
  <wp:post_date>2024-03-26 20:36:33</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:36:33</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:36:33</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:36:33</wp:post_modified_gmt>
  <wp:comment_status>closed</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>navigation</wp:post_name>
  <wp:status>publish</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>wp_navigation</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
</item>
<item>
  <title><![CDATA[descarga (4)]]></title>
  <link>https://digu33.wordpress.com/descarga-4/</link>
  <pubDate>Wed, 27 Mar 2024 01:28:11 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">http://digu33.files.wordpress.com/2024/03/descarga-4.jpg</guid>
  <description/>
  <content:encoded><![CDATA[]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>16</wp:post_id>
  <wp:post_date>2024-03-26 20:28:11</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:28:11</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:28:11</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:28:11</wp:post_modified_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>descarga-4</wp:post_name>
  <wp:status>inherit</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>attachment</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <wp:attachment_url>https://digu33.wordpress.com/wp-content/uploads/2024/03/descarga-4.jpg</wp:attachment_url>
  <wp:postmeta>
    <wp:meta_key>_wp_attached_file</wp:meta_key>
    <wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/descarga-4.jpg]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wp_attachment_metadata</wp:meta_key>
    <wp:meta_value><![CDATA[a:6:{s:5:"width";i:225;s:6:"height";i:225;s:4:"file";s:87:"/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/descarga-4.jpg";s:8:"filesize";i:8569;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[Custom Styles]]></title>
  <link>https://digu33.wordpress.com/2024/03/26/wp-global-styles-pub%2ffreddie/</link>
  <pubDate>Wed, 27 Mar 2024 01:32:47 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">https://digu33.wordpress.com/2024/03/26/wp-global-styles-pub%2ffreddie/</guid>
  <description/>
  <content:encoded><![CDATA[{"version":2,"isGlobalStylesUserThemeJSON":true}]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>18</wp:post_id>
  <wp:post_date>2024-03-26 20:32:47</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:32:47</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:32:47</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:32:47</wp:post_modified_gmt>
  <wp:comment_status>closed</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>wp-global-styles-pub%2ffreddie</wp:post_name>
  <wp:status>publish</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>wp_global_styles</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <category domain="wp_theme" nicename="freddie"><![CDATA[freddie]]></category>
  <wp:postmeta>
    <wp:meta_key>_publicize_pending</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[El arte de la conexión]]></title>
  <link>https://digu33.wordpress.com/2024/03/26/el-arte-de-la-conexion-2/</link>
  <pubDate>Wed, 27 Mar 2024 01:31:18 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">https://digu33.wordpress.com/2024/03/26/el-arte-de-la-conexion-2/</guid>
  <description/>
  <content:encoded><![CDATA[<!-- wp:paragraph -->
<p>Te damos la bienvenida a WordPress. Esta es una entrada de ejemplo. Empieza tu andadura en el mundo bloguero editándola o borrándola. Para añadir más contenido aquí, haz clic en el pequeño icono del signo más situado en la esquina superior izquierda. Allí encontrarás una selección de bloques y patrones de WordPress que se adaptan a todas tus necesidades de creación de contenidos. Y no te olvides de echar un vistazo a la vista de lista: haz clic en el icono que hay unos puntos a la derecha del icono del signo más y obtendrás una lista ordenada y fácil de ver de los bloques y patrones de tu entrada.</p>
<!-- /wp:paragraph -->]]></content:encoded>
  <excerpt:encoded><![CDATA[En un mundo en constante evolución, el arte de forjar conexiones genuinas sigue siendo atemporal. Ya sea con compañeros, clientes o socios, establecer una relación auténtica allana el camino hacia el éxito de la colaboración.]]></excerpt:encoded>
  <wp:post_id>19</wp:post_id>
  <wp:post_date>2024-03-26 20:31:18</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:31:18</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:31:18</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:31:18</wp:post_modified_gmt>
  <wp:comment_status>closed</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>el-arte-de-la-conexion-2</wp:post_name>
  <wp:status>publish</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>post</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <category domain="category" nicename="sin-categoria"><![CDATA[Sin categoría]]></category>
  <wp:postmeta>
    <wp:meta_key>_jetpack_memberships_contains_paywalled_content</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_jetpack_memberships_contains_paid_content</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_headstart_post</wp:meta_key>
    <wp:meta_value><![CDATA[_hs_extra]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>sharing_disabled</wp:meta_key>
    <wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>switch_like_status</wp:meta_key>
    <wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_starter_page_template</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_hs_old_id</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wpas_skip_all_services</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_publicize_pending</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_thumbnail_id</wp:meta_key>
    <wp:meta_value><![CDATA[25]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[Más allá del obstáculo]]></title>
  <link>https://digu33.wordpress.com/2024/03/26/mas-alla-del-obstaculo-2/</link>
  <pubDate>Wed, 27 Mar 2024 01:31:17 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">https://digu33.wordpress.com/2024/03/26/mas-alla-del-obstaculo-2/</guid>
  <description/>
  <content:encoded><![CDATA[<!-- wp:paragraph -->
<p>Te damos la bienvenida a WordPress. Esta es una entrada de ejemplo. Empieza tu andadura en el mundo bloguero editándola o borrándola. Para añadir más contenido aquí, haz clic en el pequeño icono del signo más situado en la esquina superior izquierda. Allí encontrarás una selección de bloques y patrones de WordPress que se adaptan a todas tus necesidades de creación de contenidos. Y no te olvides de echar un vistazo a la vista de lista: haz clic en el icono que hay unos puntos a la derecha del icono del signo más y obtendrás una lista ordenada y fácil de ver de los bloques y patrones de tu entrada.</p>
<!-- /wp:paragraph -->]]></content:encoded>
  <excerpt:encoded><![CDATA[Los retos en los negocios son un hecho, pero es nuestra respuesta a ellos lo que define nuestra trayectoria. Mirando más allá del obstáculo inmediato, existe un reino de oportunidades y aprendizaje.]]></excerpt:encoded>
  <wp:post_id>20</wp:post_id>
  <wp:post_date>2024-03-26 20:31:17</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:31:17</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:31:17</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:31:17</wp:post_modified_gmt>
  <wp:comment_status>closed</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>mas-alla-del-obstaculo-2</wp:post_name>
  <wp:status>publish</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>post</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <category domain="category" nicename="sin-categoria"><![CDATA[Sin categoría]]></category>
  <wp:postmeta>
    <wp:meta_key>_publicize_pending</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wpas_skip_all_services</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_hs_old_id</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_starter_page_template</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>switch_like_status</wp:meta_key>
    <wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>sharing_disabled</wp:meta_key>
    <wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_headstart_post</wp:meta_key>
    <wp:meta_value><![CDATA[_hs_extra]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_jetpack_memberships_contains_paywalled_content</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_jetpack_memberships_contains_paid_content</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_thumbnail_id</wp:meta_key>
    <wp:meta_value><![CDATA[26]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[Triunfo del trabajo en equipo]]></title>
  <link>https://digu33.wordpress.com/2024/03/26/triunfo-del-trabajo-en-equipo-2/</link>
  <pubDate>Wed, 27 Mar 2024 01:31:14 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">https://digu33.wordpress.com/2024/03/26/triunfo-del-trabajo-en-equipo-2/</guid>
  <description/>
  <content:encoded><![CDATA[<!-- wp:paragraph -->
<p>Te damos la bienvenida a WordPress. Esta es una entrada de ejemplo. Empieza tu andadura en el mundo bloguero editándola o borrándola. Para añadir más contenido aquí, haz clic en el pequeño icono del signo más situado en la esquina superior izquierda. Allí encontrarás una selección de bloques y patrones de WordPress que se adaptan a todas tus necesidades de creación de contenidos. Y no te olvides de echar un vistazo a la vista de lista: haz clic en el icono que hay unos puntos a la derecha del icono del signo más y obtendrás una lista ordenada y fácil de ver de los bloques y patrones de tu entrada.</p>
<!-- /wp:paragraph -->]]></content:encoded>
  <excerpt:encoded><![CDATA[¿Qué fomenta un trabajo en equipo eficaz? No se trata solo de agrupar individuos y esperar lo mejor. Se trata de cultivar un entorno en el que converjan la confianza, la comunicación abierta, el respeto mutuo y una visión compartida.]]></excerpt:encoded>
  <wp:post_id>23</wp:post_id>
  <wp:post_date>2024-03-26 20:31:14</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:31:14</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:31:14</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:31:14</wp:post_modified_gmt>
  <wp:comment_status>closed</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>triunfo-del-trabajo-en-equipo-2</wp:post_name>
  <wp:status>publish</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>post</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <category domain="category" nicename="sin-categoria"><![CDATA[Sin categoría]]></category>
  <wp:postmeta>
    <wp:meta_key>_starter_page_template</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>switch_like_status</wp:meta_key>
    <wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>sharing_disabled</wp:meta_key>
    <wp:meta_value><![CDATA[a:1:{i:0;N;}]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_headstart_post</wp:meta_key>
    <wp:meta_value><![CDATA[_hs_extra]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_jetpack_memberships_contains_paywalled_content</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_jetpack_memberships_contains_paid_content</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_hs_old_id</wp:meta_key>
    <wp:meta_value><![CDATA[]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wpas_skip_all_services</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_publicize_pending</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[Placeholder Image]]></title>
  <link>https://digu33.wordpress.com/2024/03/26/el-arte-de-la-conexion-2/placeholder-image-4/</link>
  <pubDate>Wed, 27 Mar 2024 01:36:27 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">http://digu33.files.wordpress.com/2024/03/0565b-tt4_post_1-1.jpg</guid>
  <description/>
  <content:encoded><![CDATA[]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>25</wp:post_id>
  <wp:post_date>2024-03-26 20:36:27</wp:post_date>
  <wp:post_date_gmt>2024-03-27 01:36:27</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 20:36:27</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 01:36:27</wp:post_modified_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>placeholder-image-4</wp:post_name>
  <wp:status>inherit</wp:status>
  <wp:post_parent>19</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>attachment</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <wp:attachment_url>https://digu33.wordpress.com/wp-content/uploads/2024/03/0565b-tt4_post_1-1.jpg</wp:attachment_url>
  <wp:postmeta>
    <wp:meta_key>_wp_attachment_metadata</wp:meta_key>
    <wp:meta_value><![CDATA[a:6:{s:5:"width";i:800;s:6:"height";i:1158;s:4:"file";s:95:"/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/0565b-tt4_post_1-1.jpg";s:8:"filesize";i:81573;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wp_attached_file</wp:meta_key>
    <wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/0565b-tt4_post_1-1.jpg]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[images (1)]]></title>
  <link>https://digu33.wordpress.com/images-1/</link>
  <pubDate>Wed, 27 Mar 2024 02:01:09 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">http://digu33.files.wordpress.com/2024/03/images-1.jpg</guid>
  <description/>
  <content:encoded><![CDATA[]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>33</wp:post_id>
  <wp:post_date>2024-03-26 21:01:09</wp:post_date>
  <wp:post_date_gmt>2024-03-27 02:01:09</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 21:01:09</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 02:01:09</wp:post_modified_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>images-1</wp:post_name>
  <wp:status>inherit</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>attachment</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <wp:attachment_url>https://digu33.wordpress.com/wp-content/uploads/2024/03/images-1.jpg</wp:attachment_url>
  <wp:postmeta>
    <wp:meta_key>_wp_attached_file</wp:meta_key>
    <wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/images-1.jpg]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wp_attachment_metadata</wp:meta_key>
    <wp:meta_value><![CDATA[a:6:{s:5:"width";i:276;s:6:"height";i:183;s:4:"file";s:85:"/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/images-1.jpg";s:8:"filesize";i:12455;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[cuadro-stranger-churchill1]]></title>
  <link>https://digu33.wordpress.com/cuadro-stranger-churchill1/</link>
  <pubDate>Wed, 27 Mar 2024 02:06:06 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">http://digu33.files.wordpress.com/2024/03/cuadro-stranger-churchill1.jpg</guid>
  <description/>
  <content:encoded><![CDATA[]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>34</wp:post_id>
  <wp:post_date>2024-03-26 21:06:06</wp:post_date>
  <wp:post_date_gmt>2024-03-27 02:06:06</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 21:06:06</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 02:06:06</wp:post_modified_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>cuadro-stranger-churchill1</wp:post_name>
  <wp:status>inherit</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>attachment</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <wp:attachment_url>https://digu33.wordpress.com/wp-content/uploads/2024/03/cuadro-stranger-churchill1.jpg</wp:attachment_url>
  <wp:postmeta>
    <wp:meta_key>_wp_attached_file</wp:meta_key>
    <wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/cuadro-stranger-churchill1.jpg]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wp_attachment_metadata</wp:meta_key>
    <wp:meta_value><![CDATA[a:6:{s:5:"width";i:935;s:6:"height";i:935;s:4:"file";s:103:"/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/cuadro-stranger-churchill1.jpg";s:8:"filesize";i:96209;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[manzana-freecoaster-odyssey-clutch-v2-400x400]]></title>
  <link>https://digu33.wordpress.com/manzana-freecoaster-odyssey-clutch-v2-400x400/</link>
  <pubDate>Wed, 27 Mar 2024 02:10:28 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">http://digu33.files.wordpress.com/2024/03/manzana-freecoaster-odyssey-clutch-v2-400x400-1.jpg</guid>
  <description/>
  <content:encoded><![CDATA[]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>35</wp:post_id>
  <wp:post_date>2024-03-26 21:10:28</wp:post_date>
  <wp:post_date_gmt>2024-03-27 02:10:28</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 21:10:28</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 02:10:28</wp:post_modified_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>manzana-freecoaster-odyssey-clutch-v2-400x400</wp:post_name>
  <wp:status>inherit</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>attachment</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <wp:attachment_url>https://digu33.wordpress.com/wp-content/uploads/2024/03/manzana-freecoaster-odyssey-clutch-v2-400x400-1.jpg</wp:attachment_url>
  <wp:postmeta>
    <wp:meta_key>_wp_attached_file</wp:meta_key>
    <wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/manzana-freecoaster-odyssey-clutch-v2-400x400-1.jpg]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wp_attachment_metadata</wp:meta_key>
    <wp:meta_value><![CDATA[a:6:{s:5:"width";i:400;s:6:"height";i:400;s:4:"file";s:124:"/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/manzana-freecoaster-odyssey-clutch-v2-400x400-1.jpg";s:8:"filesize";i:32069;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[Header]]></title>
  <link>https://digu33.wordpress.com/2024/03/26/header/</link>
  <pubDate>Wed, 27 Mar 2024 02:17:05 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">https://digu33.wordpress.com/2024/03/26/header/</guid>
  <description/>
  <content:encoded><![CDATA[<!-- wp:group {"align":"wide","style":{"spacing":{"padding":{"top":"20px","bottom":"20px"}}},"backgroundColor":"base","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide has-base-background-color has-background" style="padding-top:20px;padding-bottom:20px"><!-- wp:group {"align":"wide","layout":{"type":"flex","justifyContent":"space-between","flexWrap":"wrap"}} -->
<div class="wp-block-group alignwide"><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|20"},"layout":{"selfStretch":"fit","flexSize":null}},"layout":{"type":"flex"}} -->
<div class="wp-block-group"><!-- wp:site-logo {"width":113,"shouldSyncIcon":false} /-->

<!-- wp:group {"style":{"spacing":{"blockGap":"0px"}}} -->
<div class="wp-block-group"><!-- wp:site-title {"level":0} /--></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:navigation {"ref":28,"layout":{"type":"flex","justifyContent":"right","orientation":"horizontal"},"style":{"spacing":{"margin":{"top":"0"},"blockGap":"var:preset|spacing|20"},"layout":{"selfStretch":"fit","flexSize":null}}} /--></div>
<!-- /wp:group --></div>
<!-- /wp:group -->]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>36</wp:post_id>
  <wp:post_date>2024-03-26 21:17:05</wp:post_date>
  <wp:post_date_gmt>2024-03-27 02:17:05</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 21:17:05</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 02:17:05</wp:post_modified_gmt>
  <wp:comment_status>closed</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>header</wp:post_name>
  <wp:status>publish</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>wp_template_part</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <category domain="wp_template_part_area" nicename="header"><![CDATA[header]]></category>
  <category domain="wp_theme" nicename="twentytwentyfour"><![CDATA[twentytwentyfour]]></category>
  <wp:postmeta>
    <wp:meta_key>origin</wp:meta_key>
    <wp:meta_value><![CDATA[theme]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_publicize_pending</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title><![CDATA[images (2)]]></title>
  <link>https://digu33.wordpress.com/images-2/</link>
  <pubDate>Wed, 27 Mar 2024 02:18:50 +0000</pubDate>
  <dc:creator>xk5dd6dzhw</dc:creator>
  <guid isPermaLink="false">http://digu33.files.wordpress.com/2024/03/images-2.jpg</guid>
  <description/>
  <content:encoded><![CDATA[]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>38</wp:post_id>
  <wp:post_date>2024-03-26 21:18:50</wp:post_date>
  <wp:post_date_gmt>2024-03-27 02:18:50</wp:post_date_gmt>
  <wp:post_modified>2024-03-26 21:18:50</wp:post_modified>
  <wp:post_modified_gmt>2024-03-27 02:18:50</wp:post_modified_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>closed</wp:ping_status>
  <wp:post_name>images-2</wp:post_name>
  <wp:status>inherit</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>attachment</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <wp:attachment_url>https://digu33.wordpress.com/wp-content/uploads/2024/03/images-2.jpg</wp:attachment_url>
  <wp:postmeta>
    <wp:meta_key>_wp_attached_file</wp:meta_key>
    <wp:meta_value><![CDATA[/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/images-2.jpg]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wp_attachment_metadata</wp:meta_key>
    <wp:meta_value><![CDATA[a:6:{s:5:"width";i:300;s:6:"height";i:168;s:4:"file";s:85:"/home/wpcom/public_html/wp-content/blogs.dir/59c/231286805/files/2024/03/images-2.jpg";s:8:"filesize";i:11326;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
  </wp:postmeta>
</item>
  </channel>
</rss>
